services:
  app:
    build: .
    ports: 
      - "8001:8001"  # what does it do? -> maps internal port "8001" to external port "8001"
    # this has to be app/app because: "Volume Mounting: The volumes directive ./app:/usr/src/app is 
    # meant to mount the app directory from your local machine into the container's /usr/src/app/ directory. 
    # However, since your app directory on the host machine might be empty or misconfigured, it ends up 
    # overriding what's inside /usr/src/app/ with an empty app directory in the container." 
    # - see https://chatgpt.com/share/1d06d7e0-9f0a-4d79-9668-02416b4e8c8b
    volumes:
      - ./app:/usr/src/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload
    env_file:
      - ./.env
    depends_on:
      - surrealdb

  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    ports:
      - '8000:8000'
    command:
      - start #start the SurrealDB server
      - --log=trace #no idea what this does :(
      - --user=root #default user
      - --pass=root #default password
    restart: always