services:
  app:
    build: .
    restart: always
    ports: 
      - "8001:8001"
    volumes:
      - ./app:/usr/src/app/app
    command: /app/.venv/bin/uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload
    environment:
      APP_URL: http://0.0.0.0:8001
      REDIS_URL: redis://redis:6379
      SURREALDB_URL: ws://surrealdb:8000/rpc
      # !!! use ->http<- localhost:8000 in surrealist !!!
      SURREALDB_USER: root
      SURREALDB_PASS: root
      SURREALDB_NAMESPACE: test
      SURREALDB_DATABASE: test
    env_file:
      - ./.env
    depends_on:
      - surrealdb
      - redis

  surrealdb:
    image: surrealdb/surrealdb:v1.5.5
    container_name: surrealdb
    ports:
      - '8000:8000'
    command:
      - start #start the SurrealDB server
      - --log=trace #no idea what this does :(
      - --user=root #default user
      - --pass=root #default password
    # the following 3 lines are a new try to see if persistent memory is working, take it out if not
      - file:/data/database.db
    volumes:
      - ./surreal_data:/data
    restart: always

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"