services:
  app:
    build: .
    restart: always
    ports: 
      - "8001:8001"
    volumes:
      - ./app:/usr/src/app/app
    command: /app/.venv/bin/uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload
    environment:
      APP_URL: ${APP_URL}
      REDIS_URL: ${REDIS_URL}
      SURREALDB_URL: ${SURREALDB_URL}
      # !!! use ->http<- localhost:8000 in surrealist !!!
      SURREALDB_USER: ${SURREALDB_USER}
      SURREALDB_PASS: ${SURREALDB_PASS}
      SURREALDB_NAMESPACE: ${SURREALDB_NAMESPACE}
      SURREALDB_DATABASE: ${SURREALDB_DATABASE}
    env_file:
      - ./.env
    depends_on:
      - surrealdb
      - redis

  surrealdb:
    image: surrealdb/surrealdb:v1.5.5
    container_name: surrealdb
    ports:
      - '8000:8000'
    command:
      - start 
      - --log=trace 
      - --user=${SURREALDB_USER} #default user
      - --pass=${SURREALDB_PASS} #default password
    # the following 3 lines are for persistant memory for local development
      - file:/data/database.db
    volumes:
      - ./surreal_data:/data
    restart: always

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"