services:
  app:
    build: .
    restart: always
    ports: 
      - "8001:8001"  # what does it do? -> maps internal port "8001" to external port "8001"
    # this has to be app/app because: "Volume Mounting: The volumes directive ./app:/usr/src/app is 
    # meant to mount the app directory from your local machine into the container's /usr/src/app/ directory. 
    # However, since your app directory on the host machine might be empty or misconfigured, it ends up 
    # overriding what's inside /usr/src/app/ with an empty app directory in the container." 
    # - see https://chatgpt.com/share/1d06d7e0-9f0a-4d79-9668-02416b4e8c8b
    volumes:
      - ./app:/usr/src/app/app
    command: /app/.venv/bin/uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload
    environment:
      APP_URL: http://0.0.0.0:8001
      SURREALDB_URL: ws://surrealdb:8000/rpc
      # !!! use ->http<- localhost:8000 in surrealist !!!
      SURREALDB_USER: root
      SURREALDB_PASS: root
      SURREALDB_NAMESPACE: test
      SURREALDB_DATABASE: test
    env_file:
      - ./.env
    depends_on:
      - surrealdb

  surrealdb:
    image: surrealdb/surrealdb:v1.5.5
    container_name: surrealdb
    ports:
      - '8000:8000'
    command:
      - start #start the SurrealDB server
      - --log=trace #no idea what this does :(
      - --user=root #default user
      - --pass=root #default password
    # the following 3 lines are a new try to see if persistent memory is working, take it out if not
      - file:/data/database.db
    volumes:
      - ./surreal_data:/data
    restart: always