app = "scanlytics-redis"
primary_region = "ams"

[build]
image = "redis:alpine"

[[services]]
internal_port = 6379
protocol = "tcp"

  [[services.ports]]
  port = 6379

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "256mb"
