# fly.toml app configuration file generated for scanlyticsbe-red-cloud-8095 on 2024-09-03T13:42:12+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "scanlyticsbe-red-cloud-8095"
primary_region = "ams"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[processes]
  app = "/path/to/your/venv/bin/uvicorn scanlyticsbe.app.main:app --host 0.0.0.0 --port 8000 --workers 1 --reload"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
